services:
  basic_ml_api:
      build:
        context: .
        args:
          VERSION: ${VERSION:-dev}
        tags:
          - "basic_ml_api:${VERSION:-dev}"
      image: basic_ml_api:${VERSION:-dev}
      container_name: basic_ml_api
      restart: unless-stopped
      volumes:
        - ./data:/usr/src/app/data
      ports:
        - 12021:5000
      env_file:
        - path: .env
          required: false

