version:  '3'
services:
  badic_ml_api:
      build: 
        context: .
        args:
          VERSION: ${VERSION}
        tags:
          - "badic_ml_api:${VERSION}"
      container_name: basic_ml_api
      restart: unless-stopped
      volumes:
        - ./data:/usr/src/app/myapp/data
      ports:
        - 12021:5000
      env_file:
        - .env

