name: Docker Image CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract version from pyproject.toml
      id: get_version
      run: echo "VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = \"(.*)\"/\1/')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp:${{ env.VERSION }} -f Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name myapp-container myapp:${{ env.VERSION }}

    - name: health check
      run: |
          for i in {0..6}; do
            curl -f http://localhost:5000/health && exit 0
            echo "Attempt $i failed, waiting 9 seconds..."
            sleep 9
          done
          exit 1

    - name: Show Docker logs on Test failure
      if: failure()
      run: |
          echo "=== Docker Container Status ==="
          docker ps -a
          echo "=== Docker Container Logs ==="
          docker logs myapp-container

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Gibhub Actions - build
        fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ALARM }} # required
      if: always() # Pick up events even if the job fails or is canceled.

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/docker/basic_ml_api/"

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/docker/basic_ml_api
          echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" > .env
          echo "VERSION=${{ steps.get_version.outputs.VERSION }}" >> .env
          docker compose down --rmi all
          docker compose build --no-cache
          docker compose up -d

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Gibhub Actions - deploy
        fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
        mention: here
        if_mention: failure,cancelled
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ALARM }} # required
      if: always() # Pick up events even if the job fails or is canceled.